### ISSUE TITLE
دایرکت شدن اپلیکیشن های موبایل

### ISSUE THREAD

**Issue by alirezasamavarchi** [Chocolate4U/Iran-v2ray-rules#12]
سلام، یه درخواست داشتم، نمیدونم میشه یا نه
اونم اینکه آیا میشه اپلیکیشن های موبایل ایرانی مثل my irancell رو دایرکت کرد ؟
چون وقتی پروکسی روشن باشه وارد نمیشه و حتما باید خاموش کرد پروکسی رو

**Comment by Chocolate4U** [comment]
سلام
هسته های v2ray و xray این قابلیت رو ندارن مگر اینکه در سمت کلاینت اعمال بشه.
هسته های clash ، clash.meta و sing-box این قابلیت رو دارند، برای clash/clash.meta میتونید به مخزن [Iran-clash-rules](https://github.com/Chocolate4U/Iran-clash-rules) مراجعه کنید و برای sing-box هم کافیه در تنظیمات [tun](https://sing-box.sagernet.org/configuration/inbound/tun/) در قسمت "exclude_package" نام پکیج اپلیکیشن های مورد نظر رو وارد کنید:
```
"exclude_package": [
    "com.myirancell",
    "ir.mci.ecareapp"
  ],
```
نام پکیج های اندروید در این مخزن موجوده: 
[Iran-Android-Packages](https://github.com/Chocolate4U/Iran-Android-Packages)
