### ISSUE TITLE
درخواست بررسی

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-v2ray-rules#13]
درود

لطفا ریپو زیر را بررسی و در صورت امکان اعمال کنید
https://github.com/Chocolate4U/Iran-sing-box-rules/issues/7

با سپاس

**Comment by Chocolate4U** [comment]
https://github.com/Chocolate4U/Iran-v2ray-rules/commit/a15a8205105d6fa5abceb44d24e18707b6c755f9
