### ISSUE TITLE
درخواست اضافه شدن CDN های ایرانی به لیست IP های ایران

### ISSUE THREAD

**Issue by mmrabbani** [Chocolate4U/Iran-v2ray-rules#14]
سلام
این پروژه دو کاربرد دارد. یکی استفاده در کلاینت برای direct کردن و دیگری استفاده در سرور برای block کردن.
در هر دو حالت برای کاربر بهتر است علاوه بر IP های ایران، IP مربوط به CDN های ایرانی را هم direct/block کند.
لذا پیشنهاد می‌کنم علاوه بر پیام رسان های ایرانی، لیست CDN های ایرانی (آروان، دراک، ایران سرور، پارس پک) هم در لیست ir قرار بگیرند.

**Comment by Chocolate4U** [comment]
سلام
علت اصلی که این کتگوری ها رو در ir ادغام نکردم از ابتدا این بود که بعضی IP های این CDN ها IP PoP های خارجشون هست و زیاد معنی نداره که در ir ادغام بشه، البته بیش از 95 درصد IP این CDN ها توسط دیتابیس های MaxMind و IP2Location پوشش داده شده و در کتگوری ir موجوده، و میتونید بدون مشکلی فقط از همون ir استفاده کنین. البته فقط برای فایل های V2ray.
مشکل فقط فایل های sing-box هستن که به علت محدودیتی که دارن از هر IP فقط یه نسخه میتونه توی فایل وجود داشته باشه که یعنی این IP ها یا باید در کتگوری ir میبودن و یا در کتگوری CDN ها، که خب این یکم مشکل ساز شده چون باعث ناقص شدن کتگوری ir شده. از اونجایی که sing-box فرمت فایل ها رو توی نسخه 1.8 عوض کرده این مشکل حل میشه و احتمالا یه تغییراتی هم توی فایل های کنونی بدم که مشکل این فایل ها هم برطرف بشه.

**Comment by mmrabbani** [comment]
حرف شما کاملا درسته که بعضی پاپ سایت ها خارج از ایران هستند. ولی نکاتی که برای اون، این لیست تهیه شده در پاپ سایت ها هم وجود داره. یعنی (۱) امکان شنود ترافیک و در نتیجه فیلتر کردن سرور . (۲) از اون طرف، وجود نداشتن سایت فیلتر شده یا تحریمی بر روی این IP ها.

مشابه این موضوع را در دامنه های IR داشتیم. وقتی همه دامنه های IR را در لیست قرار می‌دهیم، منظور این نیست که همه این سایت ها در داخل ایران هستند. ولی میتوانیم بگوییم همه این سایت ها مشمول فیلتر یا تحریم نیستند و از این جهت همه دامنه های IR رو در نظر میگیریم.

در نهایت هر تصمیمی بگیرید محترم است.

**Comment by Chocolate4U** [comment]
من یه مقدار بررسی کردم، تعداد پاپ PoPs های خارجی CDN ها مخصوصا آروان خیلی کم شده، تا جایی یادمه سال گذشته بیشتر بودن. و همچنین هم حق با شماست و به شدت بعیده وبسایت خارجی ای روی این IP ها باشه. 
#17 
هر 4 CDN رو در کتگوری "ir" ادغام کردم و اون 4 کتگوری قبلی هم به جهت backward نگه داشتم.
