### ISSUE TITLE
We need your expertise

### ISSUE THREAD

**Issue by Phoenix-999** [Chocolate4U/Iran-v2ray-rules#15]
Sorry to drop the message like this here but we would like you to join our private group to discuss the issue with the gfw in Iran

https://github.com/XTLS/Xray-core/issues/2778#issuecomment-1837245571

Here is my email,be in touch 
Ronin.Parsi@proton.me

Ps: our private group is in telegram

**Comment by Chocolate4U** [comment]
Hi,
I'm not on telegram at the moment, but you can contact me via my email address on my github profile page. I would be happy to help in this regard if I can.
