### ISSUE TITLE
اضافه کردن لیست oisd

### ISSUE THREAD

**Issue by peymanhaji** [Chocolate4U/Iran-v2ray-rules#18]
سلام لیست oisd در حال حاضر جامع ترین لیست سایتهای تبلیغاتی و همچنین سایت های پورن هستش.
https://oisd.nl/
که oisd-small لیست سایتهای تبلیغاتی هست.
و oisd-big لیست سایتهای تبلیغاتی بعلاوه بدافزار و فیشینگ و ... هست.
و oisd-nsfw لیست سایتهای پورن.
جامعترین لیست در حال حاضر هستش که از منابع مختلف دائم لیستشو اپدیت میکنه.
توضیحات بیشترو میتونی در 
https://oisd.nl/faq
و
https://oisd.nl/includedlists
ببینی.
فرمتی که برای v2ray میشه استفاده کرد  سه لیست:
https://small.oisd.nl/domainswild2
https://big.oisd.nl/domainswild2
https://nsfw.oisd.nl/domainswild2
هست که لیست دامنه ها تو هر خط نوشته شده و مستقیم میتونی تبدیل به dat فایل v2ray برای پروژه کنی.(تمام ساب دامنه هایی که  دامنش در لیست هست نیز باید شامل باشه)

**Comment by Chocolate4U** [comment]
سلام
لیست oisd-small [قبلا](https://github.com/Chocolate4U/Iran-v2ray-rules/commit/94d06d14663044f489a6dedfc6a845e8db6065b4) جزو منابع ریپو بود، که با بررسی هایی که کردم با لیست [hagezi - multi light](https://github.com/hagezi/dns-blocklists#light) جایگزینش کردم، چون هم نسبت به oisd-small کاملتر بود و هم کامیونیتی فعالتری داره که به شناخت سریعتر false positive ها کمک میکنه.

لیست oisd-big هم خیلی بزرگه و در حال حاضر چیزی حدود 220 هزار دامنه داره که این حجم فایل رو خیلی بالا میبره و روی پرفورمنس هم تاثیر منفی داره، مخصوصا روی موبایل.

لیست oisd-nsfw هم به همون دلیل بالا نمیشه استفاده کرد و خیلی بزرگه.

به نظرم لیست فعلی بالانس خوبی بین بلاک کردن، حجم و تعداد دامنه ها داره و توی تست [d3ward](https://d3ward.github.io/toolz/adblock.html) امتیاز 93 رو کسب میکنه که امتیاز خوبیه.
