### ISSUE TITLE
add ninifile.com to bypass list 

### ISSUE THREAD

**Issue by mars1373** [Chocolate4U/Iran-v2ray-rules#19]
add ninifile.com to bypass list 
برای کامل باز شدن سایت  ninisite.com بایید دامنه ninifile.com هم bypass شود

**Comment by Chocolate4U** [comment]
سلام
این موارد رو به [iran-hosted-domains](https://github.com/bootmortis/iran-hosted-domains) گزارش بدین، چون سورس دامنه های ایرانی از اونجاست و بهتره اونجا این موارد صورت بگیره.
