### ISSUE TITLE
"ext:geosite_IR.dat:ir" makes Xray crash

### ISSUE THREAD

**Issue by MK0ltra** [Chocolate4U/Iran-v2ray-rules#20]
This dat files are added to this
[XUI Panel](https://github.com/alireza0/x-ui) and their names are geosite_IR.dat and geoip_IR.dat
However, when i try to add this rule to routing config, xray (1.8.6) crashed with this error. Maybe it contains illegal characters? :

"ext:geosite_IR.dat:ir"

`failed to start: main: failed to create server > netip.parseprefix("<nil>/0"): parseaddr("<nil>"): unable to parse ip`

**Comment by Chocolate4U** [comment]
Hi,
I have just tested rules with the latest xray-core and there was no problem. can you test again with the latest geo assets and give feedback?
If the issue persists, write the full routing configuration here so I can investigate further.
