### ISSUE TITLE
Confusion on understanding how to run it

### ISSUE THREAD

**Issue by mayburs** [Chocolate4U/Iran-v2ray-rules#22]
Hey there.
I read the readme part multiple times, but still couldn't figure it out.
Is there a way to explain in a little simpler for me how I can add the rules in v2rayn of my desktop?
I am slightly confused about what to do with .dat and .json and where to import them.
That would be nice of you if you provided me with step by step guide on what to do.
Thanks.

**Comment by Chocolate4U** [comment]
Hi,
If by ".json" you mean `config.json` in the root of the repo, then that's for the rule generation, you don't need that.
Download `geoip.dat`, `geosite.dat`,  `geoip.db`, `geosite.db` from release section.
Then copy and replace `geoip.dat` and `geosite.dat` to `v2rayN\bin` directory and `geoip.db` and `geosite.db` to `v2rayN\guiConfigs` directory. Also set Automatic update interval of Geo (hours) to 0 to avoid geo files getting replaced by original files. Then go to RoutingSetting > Advanced Function > Add > Rule Add , set outboundTag to direct and add `geosite:ir` to Domain section and `geoip:ir`, `geoip:private` to IP section and click Confirm. redo this process for outboundTag set to block with `geosite:category-ads-all` or other categories like `geosite:malware` (each on separate line) in Domain section.

Let me know if you need any further assistance.

**Comment by mayburs** [comment]
Thanks for your response,

I would like to know whether `geoip.db` and `geosite.db` are available in the releases section.

Cause I searched and there was no file formatted .db there.

**Comment by Chocolate4U** [comment]
`geoip.db` and `geosite.db` are for sing-box core in V2rayN. You can download them from this repository:

https://github.com/Chocolate4U/Iran-sing-box-rules

**Comment by mayburs** [comment]
Thanks for your response,
I did what you mentioned and it's working as great as it is supposed to.
Now As my final Question:
Are `geosite:malware` and `geosite:phishing` integrated in those files or I should manually download security-ip.dat and .db and then set them as a block in domain section?

**Comment by Chocolate4U** [comment]
They are integrated in `geosite` and `geoip` databases. `security` and `security-ip` databases are just a lightweight alternative for those that only need to block malware, phishing, cryptominers and ads.

**Comment by mayburs** [comment]
Got it.
I got my answers.
Thanks!
Have a nice time! :)

**Comment by mayburs** [comment]
Hello,

I appreciate all the work that has gone into this project. I was trying to configure these rules in Nekoray and V2rayNG too, but I wasn’t sure how to do it correctly.

Could you please provide some guidance on how to import and apply these rules in these applications?
