### ISSUE TITLE
قرار گرفتن آی پی سرور در فایل Geoip

### ISSUE THREAD

**Issue by StayAway32** [Chocolate4U/Iran-v2ray-rules#24]
سلام و خسته نباشید
آی پی سرور من توی فایل geoip.dat شما قرار گرفته و با این حساب مشکل ایجاد میکنه

حالا من با هر برنامه ای تلاش میکنم اینو باز کنم که فرمت binary رو بهم درست نشون بده بتونم آی پی سرورمو در بیارم از فایل نمیشه ! میشه راهنمایی کنین ؟ ممنونم

**Comment by Chocolate4U** [comment]
سلام
آی پی سرور توی کدوم لیست قرار گرفته؟
[اینجا](https://github.com/Chocolate4U/Iran-v2ray-rules/tree/release/text) لیست IP های این ریپو هست که تبدیل میشن به فایل dat
در هر صورت نیازی به این کار نیست، توی تنظیمات مسیریابی، IP سرور رو بالاتر از سایر قوانین مسیریابی قرار بدین و رول موردنظر رو بهش بدین(پروکسی، دایرکت و ...)، چون v2ray به ترتیب رول ها رو میخونه، رول موردنظر شما بر رول های بعدی تقدم داره و اصلا سراغ فایل های این ریپو برای اون IP نمیاد.

**Comment by Chocolate4U** [comment]
فایل geosite که مربوط به دامنه هاست، شما احتمالا منظورت geoip هست درسته؟
فایل dat رو که نمیشه ادیت کرد، باید این ریپو رو به همراه [geoip](https://github.com/Loyalsoldier/geoip) کلون کنید روی سیستم خودتون و IP مورد نظرتون رو پاک کنید، فایل `config.json` رو هم ادیت کنید که لیست IP ها رو از محل لیست IP های ادیت شده بگیره و بعد خروجی بگیرید ازش
