### ISSUE TITLE
درخواست 

### ISSUE THREAD

**Issue by Graveyard9988** [Chocolate4U/Iran-v2ray-rules#25]
درود
لطفا PR جهت حق انتخاب geo های شکلات برای کلاینت های زیر ثبت کنید (همانند نکوباکس) :

https://github.com/KaringX/karing

سپاس

**Comment by Chocolate4U** [comment]
درود
متاسفانه من الان کمی سرم شلوغه و وقت نمیکنم، اگر میتونید خودتون PR بزنید، در غیر اینصورت صبر کنید من سرم خلوت بشه بررسی می کنم.
