### ISSUE TITLE
پیاده سازی

### ISSUE THREAD

**Issue by hamed0mh** [Chocolate4U/Iran-v2ray-rules#26]
سلام روی برنامه v2rayN  پی سی چطوری میشه این رول ها اضافه کرد ؟

**Comment by Chocolate4U** [comment]
سلام
فایل های `geosite.dat` ، `geoip.dat` را در پوشه `v2rayN\bin` و `geosite.db` ، `geoip.db` را در پوشه `v2rayN\guiConfigs` بریزید و جایگزین کنید. از تنظیمات در سربرگ V2rayN Settings مقدار گزینه automatic update interval of geo (hours) را بر روی `1-` قرار بدید تا فایل های پیشفرض به طور خودکار جایگزین نشن.
رول ها رو هم مثل سایر آموزش ها در قسمت routing settings باید بنویسید.
