### ISSUE TITLE
یوتیوب

### ISSUE THREAD

**Issue by realartin** [Chocolate4U/Iran-v2ray-rules#28]
درود با عرض خسته نباشید و تشکر بابت این سرویس با کیفیت که در اختیار ما قرار دادید
درخواست داشتم تا در صورت امکان لیست مربوط به یوتیوب رو هم اضافه کنید و همچنین دیگر سایت ها و ... به تفکیک اضافه کنید با تشکر

**Comment by Chocolate4U** [comment]
سلام،
لیست یوتیوب و همچنین سایر لیست ها از ریپو [domain-list-community](https://github.com/v2fly/domain-list-community) در این مخزن موجوده و میتونید به این شکل استفاده کنید:
```
geosite:youtube
```
