### ISSUE TITLE
قرار گرفتن دامنه t.co به عنوان دامنه تبلیغاتی

### ISSUE THREAD

**Issue by mmrabbani** [Chocolate4U/Iran-v2ray-rules#29]
با سلام

پروژه 3x-ui از این پروژه برای پیدا کردن دامنه ها استفاده می‌کند. متوجه شدم وقتی در سرور دامنه های تبلیغاتی را می‌بندم توییتر به درستی کار نمی کند. وقتی بررسی بیشتر کردم دیدم وقتی category-ads-all از پروژه Iran-v2ray-rules بلاک می‌شود، دامنه t.co که یکی از دامنه های توییتر است هم بلاک می‌شود. چون دسته category-ads-all از پروژه های مختلفی دامنه ها را جمع می‌کند، نتوانستم متوجه شوم که مشکل از کدام پروژه است و لذا اینجا موضوع را مطرح کردم.

**Comment by Chocolate4U** [comment]
سلام
بله، این دامنه در لیست `Peter Lowe's Ad and tracking server list` قرار گرفته بود که با اینکه لیست معتبری هست اما یه مقدار زیادی افراطیه و قبلا اینجور موارد رو ازش با استفاده از لیست سفید های hagezi حذف میکردم. الان که hagezi اون لیستا رو حذف کرده این مشکل به وجود اومده بود. در کل هم اکثر دامنه های لیست `Peter Lowe` توی لیست hagezi هست، برای همین کلا لیست `Peter Lowe` رو حذف کردم.
توی ریلیز بعدی حل میشه.

**Comment by mmrabbani** [comment]
ممنون از لطف و زحمات شما
