### ISSUE TITLE
سوال

### ISSUE THREAD

**Issue by Hosseinbabaei** [Chocolate4U/Iran-v2ray-rules#30]
آیا راهی هست که در نرم‌افزار v2rayN آدرس URL فایل‌های GeoIP و GeoSite ایران رو به جای آدرس‌های پیش‌فرض چین تنظیم کنیم و به صورت خودکار به آخرین نسخه به‌روز بشه؟

و اگر راهی فعلا نیست، چطور میشه که فایل ایران رو در کنار فایل چین نگه داریم و دانلود خودکار باعث جایگزین شدن فایل چینی نشه. الان با وجود این که تنظیم شده خودکار آپدیت نشه ولی فایل Geo رو باز هم دانلود میکنه و replace میکنه.

**Comment by Chocolate4U** [comment]
سلام،
نه متاسفانه، آدرس فایل های جئو توی سورس کد برنامه hardcode شده و فقط میتونید از اونجا تغییرشون بدین و بعد دوباره برنامه رو کامپایل کنید.
اگه میخواید اتوماتیک فایل های چین رو دانلود نکنه میتونید از تنظیمات `automatic update interval of geo` رو روی `1-` بزارید.
اگر هم میخواید که در کنار فایل های چین فایل های ایران هم داشته باشید، باید اسم فایل های ایران رو به چیزی غیر از `geosite.dat` و `geoip.dat` تغییر بدین تا replace نشن.
