### ISSUE TITLE
مشکل geosite

### ISSUE THREAD

**Issue by randomguy-on-internet** [Chocolate4U/Iran-v2ray-rules#32]
سلام و درود.
امروز صبح که فایل geosite آپدیت شده بود این دو کتگوری به مشکل خورده بودن و سرور داون شده بود، میشه بررسی کنید؟
geosite: category-porn
geosite: category-github

**Comment by Chocolate4U** [comment]
سلام،
بله متاسفانه بعد از تغییرات جدید یک مشکل کوچیک وجود داشت که باعث شده بود لیست [domain-list-community](https://github.com/v2fly/domain-list-community) توی `geosite.dat` لحاظ نشه.
مشکل فیکس شد لطفا فایل ها رو آپدیت کنید.
