### ISSUE TITLE
سوال درباره ی لیست سایت های تحریم و یا فیلتر شده

### ISSUE THREAD

**Issue by BehradJi** [Chocolate4U/Iran-v2ray-rules#33]
سلام و خسته نباشید.
میخواستم ببینم دسته بندی یا لیستی برای سایت های تحریم شده و یا فیلتر شده موجود هست؟
اینو برای این میپرسم که اگه بشه فقط سایت هایی که به طور مستقیم با IP ایران باز نمیشه رو از پروکسی رد کرد خیلی خوب میشه.

**Comment by Chocolate4U** [comment]
سلام،
نه متاسفانه سورس معتبر و قابل اعتمادی برای سایت های فیلتر شده موجود نیست و درآوردن چنین لیستی و به روزرسانی اون هم کار خیلی سختیه.

**Comment by BehradJi** [comment]
خیلی ممنون.

**Comment by BehradJi** [comment]
خیلی ممنون.
