### ISSUE TITLE
روش پیشنهادی شما در ویندوز کار نمیکند.(v2rayn 6.45)

### ISSUE THREAD

**Issue by lovecontract** [Chocolate4U/Iran-v2ray-rules#35]
سلام. من تعدادی از ایشو های ارسالی کاربران رو خوندم و طبق پیشنهاد شما فایل ها ایکس ری و سینگ باکس رو در فولدر خودش گذاشتم تنظیمات بروزرسانی رو هم روی 0 یا -1 گذاشتم. منتها ارور زیر رو دریافت میکنم.
ATAL[0000] start service: initialize rule-set[3]: initial rule-set: geosite-ir: unexpected status: 404 Not Found
FATAL[0000] start service: initialize rule-set[3]: initial rule-set: geosite-ir: unexpected status: 404 Not Found
و عملا کارایی نداره.
تصویر تنظیمات رو هم ارسال میکنم.
![image](https://github.com/Chocolate4U/Iran-v2ray-rules/assets/172116369/587617e1-c86c-45dd-a0e5-c4d54f4d19be)

![image](https://github.com/Chocolate4U/Iran-v2ray-rules/assets/172116369/8915b230-0119-459f-9472-495d9e8262d4)

![image](https://github.com/Chocolate4U/Iran-v2ray-rules/assets/172116369/8b8f4541-0a9a-40a5-ad1c-4745244712c9)

**Comment by Chocolate4U** [comment]
سلام،
بله اون روش دیگه جواب نمیده، علتش هم این هست که V2rayN در آپدیت جدید دیگه از فایل های `db.` و `dat.` استفاده نمیکنه و از Rule-set استفاده میکنه که اون ها رو هم از لینک از پیش تعیین شده ای که توی [سورس کد برنامه hardcode شده](https://github.com/2dust/v2rayN/blob/63d5a2a1be046c0d802dc9fcfcc014bb193c76f5/v2rayN/v2rayN/Global.cs#L26) دانلود می کنه. در حال حاضر راهی برای تغییر لینک دانلود فایل های `srs.` از تنظیمات V2rayN وجود نداره متأسفانه.
