### ISSUE TITLE
whatsapp

### ISSUE THREAD

**Issue by realartin** [Chocolate4U/Iran-v2ray-rules#36]
درود لطفا در صورت امکان 
geoip:whatsapp
رو اضافه کنید 
[https://scontent-fra5-2.xx.fbcdn.net/v/t39.8562-6/294790302_594181512310604_1843582886070458040_n.zip?_nc_cat=109&ccb=1-7&_nc_sid=b8d81d&_nc_ohc=tD-VpCJ7FKsQ7kNvgHhHh7M&_nc_ht=scontent-fra5-2.xx&oh=00_AYDrUxlj1jg2uP9COfWb3a0Ym6OBDOTqpwaa_jmh5j3K-g&oe=6678E7CB](url)

**Comment by realartin** [comment]
https://developers.facebook.com/docs/whatsapp/guides/network-requirements?locale=en_US

**Comment by Chocolate4U** [comment]
سلام،
من IP های موجود در لینکی که گذاشتید رو بررسی کردم و همه در لیست فعلی `geoip:facebook` که در اصل IP های متا هست موجودن. از اونجایی که شرکت متا برای سرویس های مختلفش از یک سرویس توزیع محتوای واحد استفاده می کنه عملا جدا کردن این IP ها ممکن نیست.
