### ISSUE TITLE
Contributing upstream to Loyalsoldier project

### ISSUE THREAD

**Issue by OnceUponATimeInAmerica** [Chocolate4U/Iran-v2ray-rules#37]
سلام و با تشکر از زحمات بسیار مفید شما،

سوالی داشتم که آیا امکان همکاری بهتر و مستمرتر با پروژه Loyalsoldier  وجود داره؟ تا جایی که تحقیق کردم محصول خروجی اون پروژه هست که همراه با بیشتر کلاینت ها فرستاده میشه و یا حداقل دیفالت اون کلاینت ها هست.
نحوه کار اون پروژه احتمالا همونطور که خودتون هم مطلع باشید، اینه که خودش لیستی از دامین ها نداره. بلکه لیست از پروژه های دیگری رو در workflow ش کامپایل کرده که هر روز آپدیت های اون لیست ها رو میگیره و build روزانه رو با محتواشون انجام میده.   

پیشنهاد خاصم این بود که یه pull request (یکبار و برای `workflow`) از جانب شما انجام بشه برای غنی تر کردن کتوگوری سایت های ایرانی که تحت اون پروژه هستن و بطور یکجا تحت [` category-ir`](https://github.com/v2fly/domain-list-community/blob/master/data/category-ir)   آورده شدن که خودش لیسی از لیست طبقه بندی شده سایتهای ایرانیه.  
در حال حاضر این لیست در اون پروژه بطور نسبی خالی و فقیر هست و جای بهبود زیاد داره (کلا فقط چند کیلوبایته!).

اگه از این طریق، (قسمتی از) لیست شما بطور خودکار و مستمر از طریق workflow ی اون پروژه، وارد کلاینت های بیشتری بشه، شعاع و برد زحمات بسیار مفید شما هم بیشتر خواهد.

البته لیست اصلی شما هم سر جای خودش هست و خواهد بود ولی اگه قسمت مهمتر این لیست شما، به این طریقه (workflow) وارد اون فایلهای جناب Loyalsoldier  هم بشه بسیار خوب بود. اینطوری دیگه pull request های متعدد لازم نیست و اون پروژه میتونه برای قسمتی از لیست  `category-ir`  خودش، هر موقع که بیلد میزنه بطور اتوماتیک از زیر لیست شما بهره ببره (بدون اینکه اندازه  فایلهای نهایی` geoip.dat , geosite.dat `  زیاد تغییر کنه).

با تشکر.

**Comment by Chocolate4U** [comment]
سلام،
برنامه ما در اصل همین بود که تمامی وبسایت های ایرانی در مخزن [domain-list-community](https://github.com/v2fly/domain-list-community) ادغام بشه که از اونجا در ریپوهای مختلفی مثل LoyalSoldier اضافه میشد. متاسفانه به دلیل برخی مشکلات که در Issue های مخزن domain-list-community راجع بهشون بحث شد این امکان ایجاد نشد که این کار انجام بگیره و با مخالفت Maintainer های اونجا روبرو شد. ادغام مستقیم با مخزن LoyalSoldier هم دقیقا همین مشکلات رو داشت. وگرنه ترجیح من هم بر این بود که همه چیز در یک مخزن واحد بود و مشکلات فعلی سازگاری با کلاینت ها ایجاد نمیشد.
