### ISSUE TITLE
سؤال: بایپس کردن یک دامنه به‌خصوص

### ISSUE THREAD

**Issue by fakhamatia** [Chocolate4U/Iran-v2ray-rules#38]
سلام
من این مقدار رو بلاک میکنم ‍‍`geosite:nsfw`، چجوری میتونم یک دامنه خاص رو از این لیست بایپس کنم؟
داخل کلاینت های مختلف 
این مثلا داخل nekoray

![image](https://github.com/Chocolate4U/Iran-v2ray-rules/assets/20030910/49a01556-e2d7-4af3-8135-bdd7bdb4d865)

سایت `imageban.ru` همچنان بلاک هست

**Comment by Chocolate4U** [comment]
درود،
برای اینکه اون دامنه پروکسی بشه باید توی روتینگ بالاتر از `geoip:nsfw` قرار بگیره:
```
"rules": [
      {
        "domain": [
          "imageban.ru"
        ],
        "outbound": "proxy"
      },
      {
        "geosite": [
          "nsfw"
        ],
        "outbound": "block"
      }
    ]
```
 احتمالا این مورد در کانفیگی که Nekobox تولید میکنه رعایت نشده. از Custom Route استفاده کنید ببینید مشکلتون حل میشه یا خیر.

**Comment by fakhamatia** [comment]
> درود، برای اینکه اون دامنه پروکسی بشه باید توی روتینگ بالاتر از `geoip:nsfw` قرار بگیره:
> 
> ```
> "rules": [
>       {
>         "domain": [
>           "imageban.ru"
>         ],
>         "outbound": "proxy"
>       },
>       {
>         "geosite": [
>           "nsfw"
>         ],
>         "outbound": "block"
>       }
>     ]
> ```
> 
> احتمالا این مورد در کانفیگی که Nekobox تولید میکنه رعایت نشده. از Custom Route استفاده کنید ببینید مشکلتون حل میشه یا خیر.

ممنونم، کار کرد این مدلی.
بخاطر همون ترتیب بود حالت عادی رعایت نمیشه یا بهتره بگیم اصلا ترتیب بندی نداره تنظیماتش.

**Comment by fakhamatia** [comment]
یه سوال دیگه هم دارم عذرخواهی میکنم.
من DoH ادگارد استفاده میکنم، داخل لاگ دیدم سایت هایی که با رول بلاک میشن باز رکوئست DNS میزنن، یعنی کلاینت بخاطر رول بلاک میکنه سایت رو ولی همچنان درخواست DNS میزنه. چرا اینجوری؟ راه حلی داره؟ توی چند مدل کلاینت مختلف همین مشکل رو دارم.

**Comment by Chocolate4U** [comment]
> یه سوال دیگه هم دارم عذرخواهی میکنم. من DoH ادگارد استفاده میکنم، داخل لاگ دیدم سایت هایی که با رول بلاک میشن باز رکوئست DNS میزنن، یعنی کلاینت بخاطر رول بلاک میکنه سایت رو ولی همچنان درخواست DNS میزنه. چرا اینجوری؟ راه حلی داره؟ توی چند مدل کلاینت مختلف همین مشکل رو دارم.

عذر میخوام دیر جواب میدم، ایشو رو بستید متوجه سوال نشدم.

هسته sing-box قابلیت بلاک در سطح DNS رو هم داره، برای این کار باید توی قسمت DNS هم رول بنویسید. به عنوان مثال اینطوری:
```
"dns": {
    "servers": [
      {
          "tag": "dns_proxy",
          "address": "https://1.1.1.1/dns-query",
          "address_resolver": "dns_local",
          "detour": "proxy"
      },
      {
          "tag": "dns_local",
          "address": "8.8.8.8",
          "detour": "direct"
      },
      {
          "tag": "dns_block",
          "address": "rcode://refused"
      }
  ],
    "rules": [
      {
        "outbound": "any",
        "server": "dns_local"
      },
      {
        "rule_set": [
          "geosite-category-ads-all"
        ],
        "server": "dns_block",
        "disable_cache": true
      },
      {
        "domain_suffix": [
          ".ir"
        ],
        "rule_set": [
          "geosite-ir"
        ],
        "outbound": [
          "direct"
        ],
        "server": "dns_local"
      }
    ]
  },
```

برای اطلاعات بیشتر [اینجا](https://sing-box.sagernet.org/configuration/dns) رو ببین
چون از نکوباکس استفاده نمیکنم، نمیدونم که جایی داره که بشه اینو تنظیم کرد یا نه.
