### ISSUE TITLE
خطا در اتصال - احتمالا به دلیل دانلود فایل اشتباه

### ISSUE THREAD

**Issue by mmrabbani** [Chocolate4U/Iran-v2ray-rules#4]
سلام
وقتی من v2rayNG کامپایل شده توسط شما رو نصب کردم و ترافیک ایران رو بایپس کردم، اتصال خطا می‌داد و اصلا برقرار نمی‌شد. تا جایی که فهمیدم مشکل از اضافه شدن geosite:ir هست که حدس میزنم در فایل دانلود شده وجود ندارد. فکر میکنم برنامه داره فایل اشتباهی رو دانلود میکنه. چون فایل geosite این پروژه ۵ مگابایت و فایل geosite-lite این پروژه ۸۰۰ کیلوبایت است. ولی فایل دانلود شده ۱.۵ مگابایت است که احتمالا چون دسته بندی geosite:ir را ندارد، اتصال خطا می‌دهد.

**Comment by mmrabbani** [comment]
به نظر می‌رسد فایل geoip هم از پروژه شما دانلود نشده. البته چون آن فایل دسته بندی geoip:ir را دارد، خطا نمی‌دهد. ولی اگر بخواهم geoip:arvancloud رو اضافه کنم خطا می‌گیرم.

**Comment by Chocolate4U** [comment]
بعد از اینکه از قسمت Geo Assets Provider (یا ارائه دهنده فایل های مسیریابی) این ریپو رو انتخاب کردید باید از منو وارد Geo asset files و آیکون دانلود گوشه بالا رو بزنید تا فایل های جدید دانلود بشن. این کار رو انجام دادید؟

**Comment by mmrabbani** [comment]
بله درست شد. ممنون از توضیحات شما. من اشتباه کرده بودم و geo asset provider را انتخاب نکرده بودم. فکر کرده بودم همین که bypass iran را انتخاب می‌کنم، برنامه متوجه می‌شود که از فایل مربوط به ایران را بگیرد.
از آنجایی که ممکن است بقیه هم اشتباه من را انجام دهند و اتفاقا گزینه مربوط به ایران پیش‌فرض نیست، آیا امکان دارد با انتخاب bypass iran یا bypass LAN and iran، گزینه geo asset provider به صورت اتوماتیک تغییر کند.

یک پیشنهاد دیگر آنکه گزینه پیش‌فرض از official به loyalsoldier تغییر کند که backward-compatibity حفظ شود. چون نسخه های قبلی v2rayNG از loyalsoldier فایل ها را دانلود می‌کردند و ممکن است کاربر rule هایی برای خودش نوشته باشد که دسته بندی آن فقط در loyalsoldier وجود داشته باشد.

**Comment by Chocolate4U** [comment]
ممنون نکات خوبی رو اشاره کردی. یه سری تغییرات دادم که با انتخاب`Bypass Iran address then proxy`یا `Bypassing LAN and Iran address then proxy` به طور اتوماتیک asset provider انتخاب بشه و domestic dns هم در صورت انتخاب بایپس ایران به 1.1.1.1 تغییر کنه.
لطفا تست کن ببین چطوره:
https://github.com/Chocolate4U/v2rayNG/releases/tag/202309251230

**Comment by mmrabbani** [comment]
دستت درد نکنه. تست کردم کاملا درست بود
