### ISSUE TITLE
Add Iran public DNS

### ISSUE THREAD

**Issue by mmrabbani** [Chocolate4U/Iran-v2ray-rules#41]
سلام
یک لیستی که بهتره به IP های ایران اضافه بشه و اتفاقا استفاده زیادی میشه، لیست DNS server های ایرانی است.
این دو تا سایت لیستی از public DNS server های ایرانی گذاشتند که خوشبختانه همشون در لیست فعلی قرار دارند.
https://dnschecker.org/public-dns/ir
https://publicdnsserver.com/iran/
https://www.publicdns.xyz/country/ir.html
این سایت هم لیستی داده که بیشترش هم در لیست فعلی وجود داره. ۲ تا آدرس هم اشتباهه (10.202.10.22 و 4.2.2.4). چند تا آدرس در این لیست هست که لوکیشن‌شون anycast خورده و به نام ایران ثبت نشده و در نتیجه در دیتابیس فعلی نیست. هاست ایران و رادار بازی و 403
https://gameloop.ir/en/dns-2/
در صورتی که مناسب دونستید میتویند این چند تا آدرس را اضافه کنید.
10.202.10.10/31
10.202.10.202
10.202.10.102
172.29.0.100
172.29.2.100

**Comment by Chocolate4U** [comment]
https://github.com/Chocolate4U/Iran-v2ray-rules/commit/780372ed9a1bd3a321bc78235bcf5c95bbfdd171
