### ISSUE TITLE
Telegram games

### ISSUE THREAD

**Issue by Pedro-e** [Chocolate4U/Iran-v2ray-rules#42]
There is a need to add geosite and geoip for Telegram games like Vertus, Xempire, and the others.![image](https://github.com/user-attachments/assets/0765ad19-2922-4e1c-828c-da3e3dc2e34d)

**Comment by Chocolate4U** [comment]
Sorry, This is not in the scope of this repository. I suggest you do a PR to [domain-list-community](https://github.com/v2fly/domain-list-community) repository.
