### ISSUE TITLE
تشکر 

### ISSUE THREAD

**Issue by Goddess0098** [Chocolate4U/Iran-v2ray-rules#44]
مرسی برای زحمات شما که طراحی کردید این مسیر بصورت اتومات بروز بشه و مرسی برای کمک به پنل bpb من نوتیف شما رو on کردم و با اینکه میدونم نمیبینید یه ری اکشن میزارم مرسی که هستید بی منت برای ما

**Comment by Chocolate4U** [comment]
سلام،
ممنون، شما لطف دارید. خوشحالم تونستم کمک کوچکی برای مقابله با فیلترینگ ظالمانه انجام بدم.
