### ISSUE TITLE
استخراج دامنه های ایرانی

### ISSUE THREAD

**Issue by randomguy-on-internet** [Chocolate4U/Iran-v2ray-rules#5]
سلام.
چجوری میشه تمامی دامنه های ایرانی داخل فایل geosite.dat رو استخراج و در فایل تکست ذخیره کرد؟

توی [رپوی ](https://github.com/v2fly/domain-list-community) گفته شده فقط پک کردن رو توضیح داده.

**Comment by Chocolate4U** [comment]
استخراج دامنه ها از فایل `dat.` امکان پذیره اما برنامه آماده ای براش نوشته نشده یا من ندیدم حداقل.
معمولا سورس فایل ها توی ریپوها به صورت تکست موجوده اگر دنبال سورسشون هستید.
مثلا برای این ریپو از اینجا میتونید به سورس ها دسترسی داشته باشید:
https://github.com/Chocolate4U/Iran-v2ray-rules/tree/release
