### ISSUE TITLE
جدا کردن اینستاگرام، واتساپ، فیسبوک

### ISSUE THREAD

**Issue by fakhamatia** [Chocolate4U/Iran-v2ray-rules#51]
درود و خسته نباشید
میدونم محصولات متا سرور های مشترک دارند ولی چون واتساپ از فیلتر درومده امکان جدا کردن فایل آیپی هست؟
چون خیلی واتساپ کنده و با فیلترشکن هم بدتر میشه.

**Comment by saminxx** [comment]
Please exclude Whatsapp and play store for now

**Comment by fakhamatia** [comment]
> Please exclude Whatsapp and play store for now

1. این issue برای گوگل پلی نیست
2. توصیه میشه گوگل پلی رو دایرکت نکنید چون پر از اپ های تحریم شده برای منطقه ایرانه و به مشکل میخورید
3. همین الان هم میتونید گوگل پلی رو دایرکت کنید با `geosite:google-play`
4. همین الان هم میتونید واتساپ رو دایرکت کنید با `geosite:whatsapp` من برای رنج آیپی ایشو زدم

**Comment by Chocolate4U** [comment]
سلام،
متاسفانه سورس قابل اتکایی برای این کار وجود نداره. خود فیسبوک هم توی لینک زیر توصیه کرده که بر اساس hostname عمل بشه و نه بر اساس IP، چون که IP ها مدام در حال تغییر هستن:
[https://developers.facebook.com/docs/whatsapp/guides/network-requirements](https://developers.facebook.com/docs/whatsapp/guides/network-requirements/)
توی همین لینک هم لیستی که فیسبوک ارائه داده مربوط به 2 سال پیشه.
توی این لینک هم گفته شده که دیگه لیست IP ها از طریق وبسایت ارائه نمیشه و صرفا برای اپراتورهای موبایل لیستی رو از طریق پورتال همکاری برای اون اپراتورها ارائه میدن.
[https://www.whatsapp.com/cidr.txt](https://www.whatsapp.com/cidr.txt)
